package Visao;

import Controller.CTRLConta;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gualter Albino
 */
public class TelaConsulta extends javax.swing.JFrame {

    private CTRLConta contaCtrl;

    public TelaConsulta() {
        initComponents();

        //Instancia o controlador
        contaCtrl = new CTRLConta();
    }

    public void ConsultarRegistros() {
        String conteudo = ConteudoInput.getText();
        if (CamposSelect.getSelectedItem().equals("Nome")) {
            ConsultarPorNome(conteudo);
        } else {
            ConsultarPorNumero(conteudo);
        }

    }

    public void ConsultarPorNumero(String conteudo) {
        String[][] registros = contaCtrl.consultarPorNumero(conteudo);
        AlimentarTabela(registros);
    }

    public void ConsultarPorNome(String conteudo
    ) {
        String[][] registros = contaCtrl.consultarPorNome(conteudo);
        AlimentarTabela(registros);
    }

    public void AlimentarTabela(String[][] registros) {
        DefaultTableModel table = (DefaultTableModel) TabelaConsulta.getModel();

        table.setRowCount(0);
        for (var i = 0; i < registros.length; i++) {
            table.addRow(new Object[]{
                registros[i][0], // Codigo
                registros[i][1], // Nome
                registros[i][2], // Agencia
                registros[i][3], // Numero
                registros[i][4], // Saldo
            });

        }

    }

    public String SetarRegistro() {
        int linhaSelecionada = TabelaConsulta.getSelectedRow();

        if (linhaSelecionada != -1) {
            DefaultTableModel tabela = (DefaultTableModel) TabelaConsulta.getModel();
            String codigo = tabela.getValueAt(linhaSelecionada, 3).toString();
            
            System.out.println(codigo);
            return codigo;
        }

        return null; // Retorna null se nenhum contato estiver selecionado
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPanel = new javax.swing.JScrollPane();
        TabelaConsulta = new javax.swing.JTable();
        CamposSelect = new javax.swing.JComboBox<>();
        ConteudoInput = new javax.swing.JTextField();
        CampoLabel = new javax.swing.JLabel();
        ConteudoLabel = new javax.swing.JLabel();
        ConsultarButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabelaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Agencia", "Numero", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaConsultaMouseClicked(evt);
            }
        });
        ScrollPanel.setViewportView(TabelaConsulta);

        CamposSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Número" }));

        CampoLabel.setText("Campo:");

        ConteudoLabel.setText("Conteudo:");

        ConsultarButton.setText("Consultar");
        ConsultarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CamposSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConteudoLabel)
                    .addComponent(ConteudoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(ConsultarButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoLabel)
                    .addComponent(ConteudoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CamposSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConteudoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ConsultarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarButtonMouseClicked
        ConsultarRegistros();
    }//GEN-LAST:event_ConsultarButtonMouseClicked

    private void TabelaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaConsultaMouseClicked
        SetarRegistro();
    }//GEN-LAST:event_TabelaConsultaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CampoLabel;
    private javax.swing.JComboBox<String> CamposSelect;
    private javax.swing.JToggleButton ConsultarButton;
    private javax.swing.JTextField ConteudoInput;
    private javax.swing.JLabel ConteudoLabel;
    private javax.swing.JScrollPane ScrollPanel;
    private javax.swing.JTable TabelaConsulta;
    // End of variables declaration//GEN-END:variables
}
